USE BookBan;
CREATE TABLE TA_FOOD(
	I_ID INT NOT NULL IDENTITY PRIMARY KEY ,
	T_NAME NVARCHAR(100) NOT NULL
)

CREATE TABLE TA_DISH(
	I_ID INT NOT NULL IDENTITY PRIMARY KEY,
	T_NAME INT NOT NULL,
	I_PRICE INT NOT NULL,
	I_FOOD INT,
	FOREIGN KEY (I_FOOD) REFERENCES TA_FOOD(I_ID)
)

CREATE TABLE TA_TABLE(
	I_ID INT NOT NULL IDENTITY PRIMARY KEY,
	T_NAME INT,
	I_X	INT NOT NULL,
	I_Y INT NOT NULL,
	B_STATUS TINYINT
)

CREATE TABLE TA_TABLE_DISH(
	I_ID INT NOT NULL IDENTITY PRIMARY KEY,
	I_TABLE INT,
	I_DISH INT,
	I_QUANTITY INT,
	D_START	DATETIME,
	D_END	DATETIME,
	T_DISH	NVARCHAR(100),
	FOREIGN KEY (I_TABLE) REFERENCES TA_TABLE(I_ID),
	FOREIGN KEY (I_DISH) REFERENCES TA_DISH(I_ID),
)

CREATE TABLE TA_INVOICE(
	I_ID INT NOT NULL IDENTITY PRIMARY KEY,
	I_TABLE_DISH INT NOT NULL,
	F_TOTAL_PRICE FLOAT NOT NULL
	
	FOREIGN KEY (I_TABLE_DISH) REFERENCES TA_TABLE_DISH(I_ID),
)

ALTER TABLE TA_DISH
ALTER COLUMN T_NAME NVARCHAR(50);
ALTER TABLE TA_TABLE
ALTER COLUMN T_NAME NVARCHAR(50);

use BookBan;

insert into TA_FOOD (T_NAME) values ('Thịt'), ('Cá'), ('Gà'), ('Tôm'), ('Cua');

INSERT INTO TA_DISH (T_NAME, I_PRICE, I_FOOD) VALUES 
('Xào', 20000, 1), 
('Hấp', 25000, 1), 
('Luộc', 15000, 1), 
('Chiên', 18000, 1), 
('Kho', 30000, 1), 
('Xào', 25000, 2), 
('Hấp', 30000, 2), 
('Chiên', 25000, 2), 
('Kho', 30000, 2), 
('Hấp', 25000, 3), 
('Luộc', 25000, 3), 
('Chiên', 15000, 3), 
('Kho', 28000, 3), 
('Xào', 25000, 4), 
('Hấp', 30000, 4), 
('Chiên', 23000, 4), 
('Xào', 40000, 5), 
('Hấp', 30000, 5);

INSERT INTO TA_TABLE (T_NAME, I_X, I_Y, B_STATUS) VALUES 
('Bàn 1', 0, 0, 1), 
('Bàn 2', 121, 0, 1), 
('Bàn 3', 242, 0, 1), 
('Bàn 4', 363, 0, 1), 
('Bàn 5', 0, 121, 1), 
('Bàn 6', 121, 121, 1), 
('Bàn 7', 242, 121, 1), 
('Bàn 8', 363, 121, 1), 
('Bàn 9', 0, 242, 1), 
('Bàn 10', 121, 242, 1);

insert into TA_TABLE_DISH (I_TABLE, I_DISH, I_QUANTITY, D_START, T_DISH) VALUES 
(1, 5, 2, CURRENT_TIMESTAMP, 'Thịt Kho'), 
(2, 8, 1, CURRENT_TIMESTAMP, 'Cá Chiên'), 
(2, 9, 1, CURRENT_TIMESTAMP, 'Cá Kho');

INSERT INTO TA_INVOICE (I_TABLE_DISH, F_TOTAL_PRICE) VALUES 
(1, 54000), 
(2, 25000), 
(3, 30000);

CREATE TABLE TA_PROMOTION (
  I_ID INT NOT NULL IDENTITY,
  I_DISH INT NOT NULL,
  F_DISCOUNT FLOAT NOT NULL,
  CONSTRAINT PK_TA_PROMOTION PRIMARY KEY (I_ID),
  CONSTRAINT TA_PROMOTION_FK FOREIGN KEY (I_DISH) REFERENCES TA_DISH (I_ID)
);

INSERT INTO TA_PROMOTION (I_DISH, F_DISCOUNT) VALUES (5, 0.1);

